# It is good practice when running analyses to save various settings outside the scripts, and call them in.
# Each time you run an analysis, save a copy of the .yml file used to run it. That way you can be sure what settings you used, even if you change them over time.
# ***** APPLIES TO ALL MODELS *****
# -> hrf information
hrf:
  pars: [1,1,0]         # Default parameters 
  deriv_bound: [0,10]   # If fitting the HRF these are the bounds (for hrf[1])
  disp_bound: [0,0]     # Generally advised to fix the dispersion value. Messing with this can get complex as you risk confounding inhibitory components 

fit_hrf : False
# -> Generic fitting information
xtol: 1e-4 #fitting tolerance
ftol: 1e-4
grid_nr: 20         #number of items in grid
rsq_threshold: 0.1  # 
#
TR: 1.05 # 1050.00ms
#
filter_predictions : False # Other options to do filtering...
n_jobs : 4 # For paralellisation, how many jobs to split off into
n_batches : 10 # For paralellisation at grid stage...
# ***** APPLIES TO PRF MODELS *****

# screen settings
screen_size_cm: 32.4 # 518.4mm  # 324.0mm
screen_distance_cm: 130
dm_edges_clipping: [0,0,0,0] # what to clip from design matrix

#unit volume RFs
normalize_RFs: False

#DM size in pixels (n_pix x n_pix) (has to be divisor of 1080)
n_pix: 100
eps: 1e-1

fixed_grid_baseline : False
# set prf amplitude
gauss_bounds : 
bold_bsl: [-3,3]
prf_ampl: [0,1000]
#Constraints
constraints : False # Determines which fitter is used. None is fastere (lGBFS), than [] (trust-constrained)
constraint_type : 'bgfs' # 'tc'

save_grids : True # Save the outputs of the grid stage?
skip_iter : False # Skip the iterative phase

# Detrend - use timeseries which have been detrended?
detrend : False
