# ***** FOR ALL MODELS 
fit_hrf : False
fixed_grid_baseline : False
# -> fitting tolerance
xtol: 0.0001
ftol: 0.0001
constraint_type : bgfs # the fast fitter. Other option is 'tc'
rsq_threshold: 0.1 
TR: 1.05 # 1050.00ms
hrf:
  pars: [1,1,0]
  deriv_bound: [0,10]
  disp_bound: [0,0]
n_jobs: 5 # number of jobs for parallel processing
skip_iter : False # skip iterative fit
detrend : 0 # Use detrended data? how many components removed?
# screen settings
screen_size_cm: 32.4 # 518.4mm  # 324.0mm
screen_distance_cm: 130
normalize_RFs: False # unit volume RFs
# **** FOR PRF (gauss) ****
gauss_bounds:
  amp_1      : [0, 1000] 
  bold_baseline  : [-5,5] 

grid_nr : 20

# ***** EXTENDED MODELS *****
# Moving beyond the gaussian model (css, dog, norm)
use_previous_gaussian_fitter_hrf : False

# Normalization model
norm:
  amp_2_grid: [0.05,0.2,0.4,0.7,1,3]
  size_2_grid: [5,8,12,18]
  b_val_grid: [0,1,10,100]
  d_val_grid: [0.1,1.0,10.0,100.0] # [1]
  amp_2_bound: [0,1000]
  b_val_bound: [0,1000]
  d_val_bound: [0.000001,1000] # [1]

# Compressive spatial summation
css:
  n_exp_grid: [0.05,0.1, 0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1,1.1]
  n_exp_bound: [0.01,3]

# Difference of gaussian
dog:
  amp_2_grid: [0.05,0.1,0.25,0.5,0.75,1,2]
  size_2_grid: [3,5,8,11,14,17,20,23,26]
  amp_2_bound: [0,1000]




